<?php
$dllist = Array
(
    0 => 'install.class.php',
    1 => 'dllist.php',
    2 => 'file/app/app/met_wechat/admin/met_wechat.class.php',
    3 => 'file/app/app/met_wechat/admin/templates/config.php',
    4 => 'file/app/app/met_wechat/admin/templates/help.php',
    5 => 'file/app/app/met_wechat/admin/templates/index.php',
    6 => 'file/app/app/met_wechat/admin/templates/js/own.js',
    7 => 'file/app/app/met_wechat/admin/templates/keywords.php',
    8 => 'file/app/app/met_wechat/admin/templates/keywords_edit.php',
    9 => 'file/app/app/met_wechat/admin/templates/menu.php',
    10 => 'file/app/app/met_wechat/admin/templates/news.php',
    11 => 'file/app/app/met_wechat/admin/templates/news_edit.php',
    12 => 'file/app/app/met_wechat/admin/templates/points.php',
    13 => 'file/app/app/met_wechat/admin/templates/reply.php',
    14 => 'file/app/app/met_wechat/admin/templates/reply_edit.php',
    15 => 'file/app/app/met_wechat/admin/templates/user.php',
    16 => 'file/app/app/met_wechat/admin/uninstall.class.php',
    17 => 'file/app/app/met_wechat/icon.png',
    18 => 'file/app/app/met_wechat/include/class/LC.class.php',
    19 => 'file/app/app/met_wechat/include/class/LW_BASE.class.php',
    20 => 'file/app/app/met_wechat/include/class/LW_REPLY.class.php',
    21 => 'file/app/app/met_wechat/include/filedata/met_wechat/index.php',
    22 => 'file/app/app/met_wechat/include/sqldata/add.sql',
    23 => 'file/app/app/met_wechat/include/sqldata/config.sql',
    24 => 'file/app/app/met_wechat/include/sqldata/update.2.0.sql',
    25 => 'file/app/app/met_wechat/lang/lang.php',
    26 => 'file/app/app/met_wechat/web/met_wechat.class.php',
    27 => 'file/app/app/met_wechat/web/templates/images/domsg_tmp.png',
    28 => 'file/app/app/met_wechat/web/templates/tmp_jf.php',
    29 => 'file/app/app/met_wechat/web/templates/tmp_lib_footer.php',
    30 => 'file/app/app/met_wechat/web/templates/tmp_lib_header.php',
    31 => 'file/app/app/met_wechat/web/templates/tmp_msg_detail.php',
    32 => 'file/app/app/met_wechat/web/templates/tmp_msg_list.php',
    33 => 'file/app/app/met_wechat/web/templates/tmp_qrcode.php',
);
?>